# blacklist
# branches:
#   except:
#     - legacy
#     - experimental

# whitelist
branches:
  only:
    - master
    - develop

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-numpy python-scipy

language: python

python:
  - "2.7"

install:
  - "pip install . --use-mirrors"
