# blacklist
# branches:
#   except:
#     - legacy
#     - experimental

# whitelist
branches:
  only:
    - master
    - develop

language: python

python:
  - "2.7"

install:
  - "pip install . --use-mirrors"
